const commandData = [
    { command: "uname", description: "Print system information" },
    { command: "uname -a", description: "Print all system information" },
    { command: "uname -s", description: "Print the kernel name" },
    { command: "uname -n", description: "Print the network node hostname" },
    { command: "uname -r", description: "Print the kernel release" },
    { command: "uname -v", description: "Print the kernel version" },
    { command: "uname -m", description: "Print the machine hardware name" },
    { command: "uname -o", description: "Print the operating system" },
    { command: "lsb_release -a", description: "Print distribution-specific information" },
    { command: "hostname", description: "Show or set the system's host name" },
    { command: "hostnamectl", description: "Control the system hostname and related settings" },
    { command: "hwinfo", description: "Probe for hardware" },
    { command: "lshw", description: "List hardware" },
    { command: "lscpu", description: "Display information about the CPU architecture" },
    { command: "lsblk", description: "List block devices" },
    { command: "lsblk -f", description: "List block devices with filesystems" },
    { command: "lspci", description: "List all PCI devices" },
    { command: "lsusb", description: "List USB devices" },
    { command: "lsusb -v", description: "List USB devices with verbose output" },
    { command: "uptime", description: "Tell how long the system has been running" },
    { command: "uptime -p", description: "Show uptime in a pretty format" },
    { command: "uptime -s", description: "Show the time the system was booted" },
    { command: "date", description: "Print or set the system date and time" },
    { command: "history", description: "Display the command history list" },
    { command: "who", description: "Show who is logged on" },
    { command: "who -w", description: "Show who is logged on and if they have messages allowed" },
    { command: "cat /proc/loadavg", description: "Show load average" },
    { command: "cat /proc/meminfo", description: "Show memory information" },
    { command: "man", description: "An interface to the on-line reference manuals" },
    { command: "man -k", description: "Search the short descriptions and manual page names" },
    { command: "man -f", description: "Display short descriptions from the manual" },
    { command: "info", description: "Read Info documents" },
    { command: "--help", description: "Display help information for a command" },
    { command: "-h", description: "Short flag for help" },
    { command: "help", description: "Display information about builtin commands" },
    { command: "whatis", description: "Display one-line manual page descriptions" },
    { command: "whatis -w", description: "Debug flag for whatis (wildcard)" },
    { command: "apropos", description: "Search the manual page names and descriptions" },
    { command: "apropos -e", description: "Search exactly for the keyword in apropos" },
    { command: "type", description: "Display information about command type" },
    { command: "type -a", description: "Display all locations containing an executable named file" },
    { command: "which", description: "Locate a command" },
    { command: "whereis", description: "Locate the binary, source, and manual page files for a command" },
    { command: "shutdown", description: "Bring the system down" },
    { command: "shutdown -r", description: "Reboot the system" },
    { command: "shutdown -P", description: "Power off the system" },
    { command: "shutdown now", description: "Shutdown immediately" },
    { command: "shutdown +10", description: "Shutdown in 10 minutes" },
    { command: "shutdown -c", description: "Cancel a pending shutdown" },
    { command: "poweroff", description: "Power off the system" },
    { command: "reboot", description: "Reboot the system" },
    { command: "halt", description: "Stop the system" },
    { command: "halt -p", description: "Stop the system and power off" },
    { command: "init 0", description: "Switch to runlevel 0 (Halt)" },
    { command: "init 1", description: "Switch to runlevel 1 (Single-user mode)" },
    { command: "init 3", description: "Switch to runlevel 3 (Multi-user mode)" },
    { command: "init 5", description: "Switch to runlevel 5 (Graphical mode)" },
    { command: "init 6", description: "Switch to runlevel 6 (Reboot)" },
    { command: "top", description: "Display Linux processes" },
    { command: "top -O %cpu", description: "Sort top by CPU usage" },
    { command: "top -O %mem", description: "Sort top by Memory usage" },
    { command: "ps", description: "Report a snapshot of the current processes" },
    { command: "mpstat", description: "Report processors related statistics" },
    { command: "free", description: "Display amount of free and used memory in the system" },
    { command: "free -h", description: "Display memory in human-readable format" },
    { command: "vmstat -s", description: "Display virtual memory statistics" },
    { command: "grep MemTotal /proc/meminfo", description: "Show total memory from meminfo" },
    { command: "slabtop", description: "Display kernel slab cache information" },
    { command: "dmesg | grep -i usb", description: "Show kernel messages related to USB" },
    { command: "lsmod", description: "Show the status of modules in the Linux Kernel" },
    { command: "ip", description: "Show / manipulate routing, devices, policy routing and tunnels" },
    { command: "ip a", description: "Show all IP addresses" },
    { command: "ip link", description: "Show network devices" },
    { command: "ip route", description: "Show routing table" },
    { command: "netstat", description: "Print network connections, routing tables, interface statistics" },
    { command: "netstat -l", description: "Show listening sockets" },
    { command: "hostname -I", description: "Display all network addresses of the host" },
    { command: "df", description: "Report file system disk space usage" },
    { command: "df -h", description: "Report file system disk space usage in human readable format" },
    { command: "du -s", description: "Summarize disk usage" },
    { command: "fdisk -l", description: "List partition tables" },
    { command: "mount", description: "Mount a filesystem" },
    { command: "findmnt", description: "Find a filesystem" },
    { command: "lsof", description: "List open files" },
    { command: "cat", description: "Concatenate files and print on the standard output" },
    { command: "grep", description: "Print lines matching a pattern" }
];
